@baseUrl = http://localhost:3000
# @jwtToken = {{authLogin.response.body.accessToken}}

# @postUuid = {{createPostOwned.response.body.id}}
# @postSlug = {{createPostOwned.response.body.slug}}
# @imagePath = {{uploadImage.response.body.url}}
# @imageUrl = {{baseUrl}}{{imagePath}}

GET {{baseUrl}}

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "fernanda@email.com",
  "password": "123456"
}

### Read One User
GET {{baseUrl}}/user/abcd

### Create user
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Fernanda Bernardes",
  "email": "fernanda1@email.com",
  "password": "123456"
}
